insert into tbl_static_data(sdata_type_id, static_data_value, static_data_label, static_data_description,created_by, created_local_date, created_UTC_date, created_nepali_date)
values (18, '1','GSM','GSM PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '2','EPIN','EPIN PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '3','TELEVISION','TELEVISION PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '4','INTERNET','INTERNET PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '5','INSURANCE','INSURANCE PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '6','ELECTRICITY','ELECTRICITY PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '7','WATER','ELECTRICITY PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '8','TICKETING','TICKETING PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '9','MEDICAL','MEDICAL PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '10','CAPITAL MARKET','CAPITAL MARKET PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '11','AGRO','AGRO PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '12','ANTIVIRUS','ANTIVIRUS PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '13','RIDE','RIDE PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '14','SHARE','SHARE MARKET PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '15','CREDIT CARD','CREDIT CARD PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '16','SCHOOL','SCHOOL PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '17','VOTING','VOTING PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '18','DELIVERY','DELIVERY PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '19','EVENT','EVENT MANAGEMENT PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '20','EMI','EMI PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default)),
(18, '21','SUBSCRIPTION','SUBSCRIPTION PRODUCTS',SESSION_USER,GETDATE(),GETUTCDATE(),dbo.func_get_nepali_date(default))