insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Cash In',5000,5000,20000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Card Fund Load',5000,5000,30000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Transfer',5000,5000,10000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Withdraw',5000,5000,20000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Card Fund Load(SCT)',5000,5000,30000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Wallet Payment',5000,5000,20000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('not verified','Load',5000,5000,30000,'system',GETDATE(),GETUTCDATE());

insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Cash In',25000,25000,100000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Card Fund Load',16000,50000,300000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Transfer',25000,100000,500000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Withdraw',25000,100000,500000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Card Fund Load(SCT)',500000,100000,500000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Wallet Payment',1000000,1000000,5000000,'system',GETDATE(),GETUTCDATE());
insert into tbl_NRB_transaction_limit(KYC_Status,txn_type,transaction_limit_max,transaction_daily_limit_max,transaction_monthly_limit_max,created_by,created_local_date,created_UTC_date) values('verified','Load',100000,1000000,1000000,'system',GETDATE(),GETUTCDATE());
