Insert into tbl_API_Response_Code (Response_Code, Response_Message, Created_by, Created_ts)
values(0, 'Success', 'admin', getdate()),
(1, 'Fail', 'admin', getdate()),
(2, 'Pending', 'admin', getdate()),
(99, 'Technical Error:', 'admin', getdate()),
(100, 'Required fields are missing', 'admin', getdate()),
(101, 'Invalid User Name or Password', 'admin', getdate()),
(102, 'Invalid or Expired Session', 'admin', getdate()),
(103, 'Invaild API Credentials', 'admin', getdate()),
(104, 'User Not Found!', 'admin', getdate()),
(105, 'Username is required!', 'admin', getdate()),
(106, 'Password is required!', 'admin', getdate()),
(107, 'Confirm Password is required!', 'admin', getdate()),
(108, 'Mobile Number is required!', 'admin', getdate()),
(109, 'Email is required!', 'admin', getdate()),
(110, 'User old password didn’t match', 'admin', getdate()),
(111, 'New Password must be more than 10 characters', 'admin', getdate()),
(112, 'User new password and confirm password didn’t match', 'admin', getdate()),
(113, 'Signature is required!', 'admin', getdate()),
(114, 'Agent Id is required!', 'admin', getdate()),
(115, 'Product Id is required!', 'admin', getdate()),
(116, 'Amount is required!', 'admin', getdate()),
(117, 'Pin Code is required!', 'admin', getdate()),
(118, 'Pin Code must be 6 characters', 'admin', getdate()),
(119, 'Authentication Error!', 'admin', getdate()),
(120, 'Invalid Signature', 'admin', getdate()),
(121, 'Registration Successful. Your Credentials will be sent via email and SMS, to your given email address and mobile number. Thank You!', 'admin', getdate()),
(122, 'Device Id is Required!', 'admin', getdate()),
(123, 'Could not connect to remote server', 'admin', getdate()),
(124, 'Could not read response from the remote server', 'admin', getdate()),
(125, 'Error Initiating Transaction', 'admin', getdate()),
(126, 'Notification Message is Empty', 'admin', getdate()),
(127, 'API password is required!', 'admin', getdate()),
(128, 'Payment Type is Required!', 'admin', getdate()),
(129, 'Sender Mobile Number is Required!', 'admin', getdate()),
(130, 'Receiver Mobile Number is Required!', 'admin', getdate()),
(131, 'Full Name is Required!', 'admin', getdate()),
(132, 'First Name is Required!', 'admin', getdate()),
(133, 'Last Name is Required!', 'admin', getdate()),
(134, 'Profile Image is Required!', 'admin', getdate()),
(135, 'Gender is Required!', 'admin', getdate()),
(136, 'Date of Birth(AD) is required!', 'admin', getdate()),
(137, 'Date of Birth (BS) is required!', 'admin', getdate()),
(138, 'Phone Number is required!', 'admin', getdate()),
(139, 'Father’s Name is required!', 'admin', getdate()),
(140, 'Grand Father’s Name is required!', 'admin', getdate()),
(141, 'Nationality is required!', 'admin', getdate()),
(142, 'Permanent Province is required!', 'admin', getdate()),
(143, 'Permanent District is required!', 'admin', getdate()),
(144, 'Permanent Local body is required!', 'admin', getdate()),
(145, 'Permanent Ward No is required!', 'admin', getdate()),
(146, 'Temporary Province is required!', 'admin', getdate()),
(147, 'Temporary Province is required!', 'admin', getdate()),
(148, 'Temporary District is required!', 'admin', getdate()),
(149, 'Temporary local body is required!', 'admin', getdate()),
(150, 'Temporary Ward No is required!', 'admin', getdate()),
(151, 'Identification type is required!', 'admin', getdate()),
(152, 'Identification No is required!', 'admin', getdate()),
(153, 'Identification Issued Place is required!', 'admin', getdate()),
(154, 'Identification Issued Date is required!', 'admin', getdate()),
(155, 'Identification Issued Date (BS) is required!', 'admin', getdate()),
(156, 'Identification expired date is required!', 'admin', getdate()),
(156, 'Identification expired date (BS) is required!', 'admin', getdate()),
(156, 'Identification document Image front is required!', 'admin', getdate()),
(156, 'Identification document Image back is required!', 'admin', getdate())