INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 1, 'Nepal Telecom', 1, 'GSM', 'NT Mobile Prepaid (GSM)', '1.ntc_pre.png', 'Please enter your NTC Prepaid Number', 'Mobile', '[0-9]', 10, 15000, 2, 7, 'Y  ', '2020-04-17 15:21:13.25', '2020-04-17 21:06:13.253', '2077-01-05', 'admin', ':1', NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 2, 'NCELL', 1, 'GSM', 'Ncell Prepaid', '2.ncell.jpg', 'Please enter your NCELL number.', 'Mobile', '[0-9]', 10, 15000, 2, 2, 'Y  ', '2020-04-17 15:23:39.247', '2020-04-17 21:08:39.247', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (0, 'MobileTopUP', 3, 'UTL', 1, 'GSM', 'UTL Mobile', '3.UTL.png', 'Please enter your UTL Prepaid/Post-Paid mobile number starting with 972 andamount to recharge your balance.', NULL, NULL, 0, 0, 2, NULL, 'Y  ', '2020-04-17 15:35:37.15', '2020-04-17 21:20:37.15', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 4, 'SMARTCELL ', 1, 'GSM', 'Smart Cell Topup', '4.smartcell_logo.png', 'Please enter your SmartCell mobile number starting with 961, 962, 988 and 989 and select amount to recharge your balance.  <br>  <br>  For more information, please click  <a target="_blank" href="http://www.smarttel.com.np">here</a>', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:35:37.19', '2020-04-17 21:20:37.193', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (2, 'Bill Payment', 1, 'Nepal Telecom ', 2, 'Rcpin', 'NT Recharge Pin', '5.Ntc_epin.jpg', 'Recharge your NTC CDMA/GSM Prepaid and CDMA Postpaid through Recharge Pin. Pleasethe denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, 0, 0, 2, NULL, 'Y', '2020-04-17 15:35:37.197', '2020-04-17 21:20:37.197', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 37, 'Movie Tickets ', 7, 'Ticketing', 'Movie Tickets', '6.movie_tickets.png', 'Book Movie Tickets of Following Cinema Halls  <br><br>  - CDC Cinemas (Kathmandu)<br>  - Gopi Krishna Cinemas (Kathmandu)<br>  - Bamel Cinemas (Banepa)<br>  - Laxmi Cinemas (Surkhet)<br><br>  ...... More Coming Soon  ', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:35:37.2', '2020-04-17 21:20:37.2', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 3, 'UTL ', 2, 'Rcpin', 'UTL Recharge Pin', '3.UTL.png', 'Recharge your UTL Mobile through Recharge Pin. Please select the denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:36:41.043', '2020-04-17 21:21:41.043', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 4, 'SMARTCELL ', 2, 'Rcpin', 'Smart Cell Recharge Pin', '4.smartcell_logo.png', 'Recharge your SmartCell Mobile through Recharge Pin. Please select the denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:37:06.813', '2020-04-17 21:22:06.813', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 1, 'Nepal Telecom ', 1, 'GSM', 'NT Mobile Prepaid (CDMA)', '9.ntc_cdma.jpg', 'Please enter your NTC CDMA Prepaid mobile number starting with 974 & 976 and select amount to recharge your balance.  <br>  <br>  For validity information, please click  <a target="_blank" href="https://www.ntc.net.np/tariff/mob_tariff.php#mpos">here</a>', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:37:40.273', '2020-04-17 21:22:40.273', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 1, 'Nepal Telecom ', 1, 'GSM', 'NT Mobile Postpaid (CDMA)', '9.ntc_cdma.jpg', 'Please enter your NTC CDMA Postpaid mobile number starting with 975 and select amount to pay your bill. <br><br>  [If your Bill Amount is NPR 450, pay NPR 500. Remaining amount (NPR 50) will be carried forward for next payment.]', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:38:05.967', '2020-04-17 21:23:05.967', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 5, 'DISHHOME ', 2, 'Rcpin', 'Dish Home Recharge Pin', '11.dish_home.png', 'Recharge your DishHome Subscription through Recharge Pin. Please select the denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:38:35.51', '2020-04-17 21:23:35.51', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 7, 'BROADLINK ', 2, 'Rcpin', 'Broadlink Recharge Pin', '12.Broadlink.jpg', 'Pay your BroadLink Internet Bill through Recharge Pin. Please select the denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:39:39.593', '2020-04-17 21:24:39.593', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 7, 'BROADLINK ', 2, 'Rcpin', 'BroadTel Recharge Pin', '12.Broadlink.jpg', 'Connect to your world with BroadTel VoIP through Recharge Pin. Please select the denomination value for your recharge card.<br /><br /> In case Recharge PIN is not working feel free to contact us.<br /><br />More Information:   <a target="_blank" href="http://broadlink.com.np/pages/broadtel">here</a>', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:40:10.773', '2020-04-17 21:25:10.773', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (1, 'MobileTopUP', 1, 'Nepal Telecom ', 1, 'GSM', 'NT Mobile Postpaid (GSM)', '14.ntc_postpaid.jpg', 'Please enter your NT Postpaid mobile number starting with 985 and select amount to pay your bill. <br><br>  [If your Bill Amount is NPR 450, pay NPR 500. Remaining amount (NPR 50) will be carried forward for next payment.]', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:42:06.633', '2020-04-17 21:27:06.633', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 1, 'Nepal Telecom ', 2, 'LandLine', 'NT Landline (PSTN / CDMA)', '15.ntc_landline.jpg', 'Please enter Nepal Telecom Landline (PSTN) or Nepal Telecom CDMA Fixed Line (C-PHONE) number starting with 0 [Format: 0&lt;Area Code&gt&lt;Telephone Number&gt] and Input amount to pay your bill.  <br><br>  [You can also make advance payment which will be carried forward for next payment.]', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:42:33.02', '2020-04-17 21:27:33.02', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 1, 'Nepal Telecom ', 4, 'Internet', 'NT ADSL Internet', '16.NT_ADSL.jpg', 'Please enter your NT Landline ADSL number starting with 0 [Format: 0&lt;Area Code&gt&lt;Telephone Number&gt] and select amount to pay your bill.  <br><br> Note: ADSL subscription must be active to make payment. Activation charges cannot be paid through us  <br>  <br>  For more detail, please click  <a target="_blank" href="https://www.ntc.net.np/pages/view/adsl-service">here</a>', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:43:07.23', '2020-04-17 21:28:07.23', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 1, 'Nepal Telecom ', 4, 'Internet', 'NT ADSL Internet Volume', '16.NT_ADSL.jpg', 'Please enter your NT Landline ADSL number starting with 0 [Format: 0&lt;Area Code&gt&lt;Telephone Number&gt]  and select amount to pay your bill.  <br><br> Note: ADSL subscription must be active to make payment. Activation charges cannot be paid through us  <br>  <br>  For validity information, please click  <a target="_blank" href="https://www.ntc.net.np/notices/payViaRecharge.php">here</a>', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:43:28.483', '2020-04-17 21:28:28.483', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 3, 'UTL ', 2, 'LandLine', 'UTL Fixed Line ', '3.UTL.png', 'Please enter your UTL Fixed Line number starting with 0  [Format: 0&lt;Area Code&gt&lt;Telephone Number&gt]  and select amount to pay your bill.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:43:41.68', '2020-04-17 21:28:41.68', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 5, 'DISHHOME ', 3, 'Television', 'DishHome Topup', '11.dish_home.png', 'CAS ID/Chip Id is Unique ID provided by Dish Media Network Pvt. Ltd. while  installing the SET TOP BOX.<br><br>To know your CAS Id check the label sticker at the back side of SET TOP BOX. SMART SET TOP BOX User can press "CAS" button in your remote control to get it on TV Screen.<br><br>Other SET TOP BOX User (SD Box user) can press "SAT" button in your remote control to get it on TV Screen or dial DishHome toll free number 1660- 01- 10101/1660-01-22000.  <br><br>If you have multiple SET TOP Box installed, please ensure that you topup Master SETTOP Box.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:43:56.033', '2020-04-17 21:28:56.033', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 33, 'NLIC ', 5, 'Insurance', 'Nepal Life Insurance', '20.NLIC.jpg', 'Please enter Nepal Life Insurance Policy Number and Click Check to get the bill amount to be paid. You should pay all the Bill Amount. Premium cannot be paid partially.<br /><br /><b>Note:</b>Premium paid to Nepal Life Insurance Ltd. realizes instantly, to collect original receipt please contact your nearest Nepal Life Insurance branch.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:44:20.58', '2020-04-17 21:29:20.58', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 32, 'Airlines ', 7, 'Ticketing', 'Domestic Air Ticketing', '21.airline_ticket.png', 'You can select air ticket of:  <br><br><b>  Buddha Air, <br>Yeti Airlines,<br>Saurya Airlines <br>Shree Airlines<br>Simrik Airlines</b>  <br><br>Compare the price of Air tickets and choose your preferred Flight.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:44:59.77', '2020-04-17 21:29:59.77', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 10, 'SUBISU', 4, 'Internet', 'SUBISU Cable / Internet', '22.Subisu.png', '- Please enter your Internet Username provided by SUBISU.<br><br>  - You have to enter customer mobile number in order to receive payment notification.<br><br>  - For e.g: If your Internet service 3 months bill is Rs 3390, pay only Rs 3289 (after 3% deduction). Your Internet service will get activated by Subisu.', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:45:14.67', '2020-04-17 21:30:14.67', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 19, 'PRABHU TV ', 3, 'Television', 'PrabhuTV OTT Topup', '23.Prabhu_tv.jpg', 'Prabhu TV Mobile OTT Service Topup', NULL, NULL, 0, 0, 2, NULL, 'Y', '2020-04-17 15:45:36.737', '2020-04-17 21:30:36.737', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 14, 'CLASSIC TECHNOLOGY ', 4, 'Internet', 'Classic Tech Internet', '28.classic_tech.jpg', 'Please enter your Username provided by Classic Tech.<br/><br/>  You will receive the electronic invoice in your registered email id after payment is completed.<br/><br/>  If you have any query, contactClassic Tech Customer Support +977- 9801004477 or write at support@classic.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:45:59.593', '2020-04-17 21:30:59.593', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 20, 'HONS ', 4, 'Internet', 'HONS Internet', '30.HONS_int.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call 01- 4244952 or send an email at pitambar@hons.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:46:24.597', '2020-04-17 21:31:24.597', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 11, 'NEA ', 5, 'Electricity', 'NEA Electricity', '31.nea_logo.png', '- Select your Payment Counter.<br><br>  - You have to enter Customer ID, SC No. and Click Get Bills<br><br>  - You will get the pending bills an customer Detail.<br><br>  - You you didn''t receive any bills pending then also you can do the Payment by entering payment amount<br><br>  - No Extra Service Charge will be applicable for this service.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:48:01.657', '2020-04-17 21:33:01.657', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 38, 'BUS TICKET ', 7, 'Ticketing', 'Domestic Bus Ticketing', '32.Bus_ticketing.jpg', 'Contact: 9801017475 / 01-4117533 for any issue related to Bus Sewa Ticketing', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:48:31.97', '2020-04-17 21:33:31.97', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 12, 'SIM TV ', 3, 'Television', 'Sim TV', '33.Sim_tv.png', '- Customer ID / CAS ID is a unique ID provided by SIM TV while installing the Set Top Box (STB) <br/>  - Customer ID will always be a 10 digits numeric number eg: 1000002345, 1000123880 <br/>  - CAS ID will always be a 11 digits numeric number started with 00 <br/>  -<span style="color:#FF0000"> No provision of refund or reconcile for wrong Customer ID Top Up. Make sure to Top Up in correct Customer ID. </span><br/>  - Recommended to keep the STB switched On at the time of Top Up for instant activation. <br/>  -<b> Any kind of Support call us at our Toll Free numbers 1660-01-44000 (NTC), 9801575703 (Ncell) <b> ', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:49:03.173', '2020-04-17 21:34:03.173', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 13, 'WORLDLINK ', 4, 'Internet', 'WorldLink Internet', '34.WordLink.jpg', 'Please enter your Worldlink UserName and search for the Plan Detail.  <br>  <br>  You will receive the electronic invoice in your email id registered after the payment gets completed.  <br>  <br>  If you have any query, contact WorldLink Account Section +977- 9801523050 or write at account@worldlink.com.np.', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:49:19.427', '2020-04-17 21:34:19.427', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 19, 'PRABHU TV ', 2, 'Rcpin', 'PrabhuTV OTT EPIN', '23.Prabhu_tv.jpg', 'This recharge card can be used to TopUp Prabhu TV OTT Mobile App Balance. <br/><br/>  Users can use this balance to buy channels and movies on Prabhu TV OTT Mobile App only <br/><br/>  <b>Note :</b> This recharge card is only valid for Prabhu TV OTT Mobile App', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:49:48.09', '2020-04-17 21:34:48.09', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 34, 'Prabhu Insurance ', 5, 'Insurance', 'Prabhu Insurance', '33.prabhu_insurance.jpg', 'Prabhu Insurance Payment', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:50:10.36', '2020-04-17 21:35:10.357', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 6, 'MERO TV ', 2, 'Rcpin', 'Mero TV Recharge Pin', '38.mero_tv.png', 'Recharge your Mero TV Subscription through Recharge Pin. Please select the denomination value for your recharge card.<br /><br />For Recharge Type:<br />MERO CASID PINNO<br />and Send SMS to 34748<br /><br /> In case Recharge PIN is not working feel free to contact us.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:50:31.667', '2020-04-17 21:35:31.667', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 9, 'VIANET ', 4, 'Internet', 'Vianet Internet', '39.Vianet.jpg', 'Please enter your Vianet UserName and search for the Plan Detail for Payment.<br><br>If you have any query or don''t know username, contact Vianet Support +977 1-4217555 or write at customercare@vianet.com.np.', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:50:49.117', '2020-04-17 21:35:49.117', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 15, 'NWSC ', 6, 'Water', 'Nepal Water Supply Bill', '40.NWSC.png', 'Please Enter Customer Id', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:51:04.307', '2020-04-17 21:36:04.307', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 16, 'UPSWB ', 6, 'Water', 'Upabhokta Samiti Water Bill', '41.USWSC.png', 'Please Enter Customer Code', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:51:24.597', '2020-04-17 21:36:24.597', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 6, 'MERO TV ', 3, 'Television', 'Mero TV Topup', '38.mero_tv.png', 'CAS ID/Smartcard ID is Unique ID provided by Mero Tv while  installing the SET TOP BOX.<br><br>  CAS ID/Smartcard ID is 10 or 11 Numeric digits starts with 3, 4 or 5<br><br>  For Billing problem contact Mero Tv, Phone: +977 1 5104646, +977 1 5104647 | NTC Toll Free number: 16600100088 | Ncell Toll Free number: 9801571088', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:51:45.277', '2020-04-17 21:36:45.277', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 1, 'Nepal Telecom ', 4, 'Internet', 'NT WiMax Internet', '44.wimax.png', 'Please enter your 9 Digit NT WiMax Subscriber number starting with 100 and select amount to Topup your WiMax Account.<br><br> Note: You need to contact WiMax Customer Support : 014239816, 014239817 or Login to SelfCare to Subscribe the WiMax Package after doing the Balance Topup  <br>  <br>  For more detail, please click  <a target="_blank" href="https://www.ntc.net.np/pages/view/wimax-broadband-internet">here</a>', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:52:03.703', '2020-04-17 21:37:03.7', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 1, 'Nepal Telecom ', 4, 'Internet', 'NT FTTH Internet', '45.nt_ftth.png', '<b>NTFTTH are of three types :</b><br>  NTFTTH Voice, NTFTTH Data and NTFTTH Combo (both voice and data)   <br>  <br>  <b>For Payment</b><br>  -If NTFTTH is data and Combo user should choose NTFTTH and Insert account number. Example 010002256 <b>(9DIGIT)</b>  <br>  -If NTFTTH is voice only than user can choose service PSTN/LANDLINE for payment. Example 010002256  <br>  <br>  For more detail, please click  <a target="_blank" href="https://www.ntc.net.np/pages/view/fiber-to-the-home-ftth">here</a>', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:52:27.707', '2020-04-17 21:37:27.707', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 18, 'SKY ', 11, 'Internet\Television', 'Sky Cable / Internet Topup', '46.sky_cable.png', '<b>For Wallet:</b> Customer ID is a unique ID provided by Sky Cable TV.<br/><br/><b>For TV:</b> Customer ID and Set Top Box No or CAS ID is a unique ID provided by Sky Cable TV while installing the Set Top Box (STB).<br/><br/><b>For Internet:</b> Customer ID and Username is a unique ID provided by Sky Cable TV while installing the internet.', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:52:46.33', '2020-04-17 21:37:46.33', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 19, 'PRABHU TV ', 3, 'Television', 'PrabhuTV Set Top Box Topup', '23.Prabhu_tv.jpg', 'CHIP / VSC ID is Unique ID provided by PrabhuTV while installing the SET TOP BOX.<br /><br />    To know your CHIP / VSC ID, check the label sticker at the back side of SET TOP BOX. <br /><br />    CHIP / VSC ID / SMART ID of PrabhiTV is 11 & 16 Numeric Digits', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:53:14.997', '2020-04-17 21:38:14.997', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 34, 'Prabhu Insurance ', 5, 'Insurance', 'Prabhu Life Insurance', '33.prabhu_insurance.jpg', 'Prabhu Life Insurance Premium Payment', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:53:42.657', '2020-04-17 21:38:42.657', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 21, 'WEBSURFER ', 4, 'Internet', 'Websurfer Internet', '51.websurfer.png', 'Customer ID is a unique ID provided by Websurfer while installing the internet.', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:54:08.357', '2020-04-17 21:39:08.36', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 22, 'ARROWNET', 4, 'Internet', 'Arrownet Internet', '52.arrownet_logo.png', 'To know your Username or in case of any issues, call +977 1 4222222 or send an email to support@arrownet.com.np.', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:55:07.98', '2020-04-17 21:40:07.98', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 23, 'TECHMINDS ', 4, 'Internet', 'Techminds Internet', '53.Techminds.jpg', 'To know your Username or in case of any issues, call 056-522222,056-531222 or send an email to info@techminds.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:55:28.57', '2020-04-17 21:40:28.57', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 24, 'Royal Network ', 4, 'Internet', 'Royal Network', '54.RoyalNetwork.jpg', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call +977 071- 546010 or send an email at info@royalnet.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:55:48.253', '2020-04-17 21:40:48.253', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 25, 'Virtual Network ', 4, 'Internet', 'Virtual Network', '55.Virtualnetwork.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call 033- 561750, 9801550690/91 or write at info@vnetwork.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:56:08.007', '2020-04-17 21:41:08.007', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 26, 'Web Network ', 4, 'Internet', 'Web Network', '56.WebNetwork.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call 071- 414623 or send an email at info@webnet.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:56:25.397', '2020-04-17 21:41:25.397', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 27, 'Pokhara Internet ', 4, 'Internet', 'Pokhara Internet', '57.PokharaNetwork.jpg', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call +977- 01- 540188 or send an email at epayment@pokharainternet.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:56:45.84', '2020-04-17 21:41:45.84', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 28, 'East Link ', 4, 'Internet', 'East Link', '58.EastLink.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call +977- 01- 4226888 or send an email at info@eastlink.net.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:57:01.123', '2020-04-17 21:42:01.123', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 35, 'Premier Insurance ', 5, 'Insurance', 'Premier Insurance', '59.PremiereInsurance.png', 'Enter Acceptance Number and Query for the Payment Amount in order to do the Payment<br /><br />  For acceptance number please contact Premier Insurance customer service department : +977-1-4413543, 4439353, premier@picl.com.np', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:57:14.413', '2020-04-17 21:42:14.413', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 36, 'Sagarmatha Insurance ', 5, 'Insurance', 'Sagarmatha Insurance', '60.SagarmathaInsurance.png', 'Please enter your Debit Note Number provided by Sagarmatha Insurance Co. Ltd.<br /><br />  You will receive the electronic payment receipt in your registered email id after payment is completed.<br /><br />  <b>Note:</b> If you have any query, contact : Sagarmatha Insurance Customer Support Toll Free Number 1660-01-66 666 Phone: +977-1-4412367 Email: customer.service@sagarmathainsurance.com.np', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:57:28.253', '2020-04-17 21:42:28.253', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 37, 'Alisha Communication', 4, 'Internet', 'Alisha Communication', '61.AlishaCommunication.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> If you have any queries contact Customer Support 9801348400/ 056-582097, 583095 or send an email at rajeev@alishalink.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:57:42.707', '2020-04-17 21:42:42.707', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 38, 'Infonet Communication', 4, 'Internet', 'Infonet Communication', '62.infonetComm.jpg', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues, call +977- 9844780000, +977- 9867200000 or (077) 420137 or send an email at info@infonetc.com.np', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:58:00.63', '2020-04-17 21:43:00.627', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 39, 'Metrolink Internet', 4, 'Internet', 'Metrolink Internet', '63.MetrolinkComm.png', 'Transaction will be processed on Internet Billing System Manually, So it may take upto 24 hours to get reflected on your Internet account. Transaction will be on Processing till get final confirmation.  <br/>  <br/>  <b>Note:</b> To know your Username or in case of any issues,Call: 071-514119,or mail on: metrolinknepal@gmail.com', NULL, NULL, NULL, NULL, 2, 7, 'Y', '2020-04-17 15:58:20.857', '2020-04-17 21:43:20.857', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 40, 'Reliance Life Insurance', 5, 'Insurance', 'Reliance Life Insurance', '64.Reliance_Life_Logo.png', 'Policy Number Should be 10 Digits and Date of Birth Should be in YYYY-MM-DD format in AD.<br/>  <br/>  Premium paid to Reliance Life Insurance Ltd. realizes instantly, to collect original receipt please contact your nearest Reliance Life branch.<br/>  <br/>  For more queries, please contact our 24*7 contact center at 01-4787224 or email us at contact.center@relifeinsurance.com', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:58:37.027', '2020-04-17 21:43:37.027', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (3, 'Bill Payment', 41, 'NLG Insurance', 5, 'Insurance', 'NLG Insurance', '65.NLGInsurance.png', 'NLG Insurance', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 15:58:52.537', '2020-04-17 21:43:52.537', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

INSERT INTO dbo.tbl_manage_services (txn_type_id, txn_type, company_id, company, product_type_id, product_type, product_label, product_logo, product_service_info, product_category, subscriber_regex, min_denomination_amount, max_denomination_amount, primary_gateway, secondary_gateway, status, created_UTC_date, created_local_date, created_nepali_date, created_by, created_ip, updated_by, updated_UTC_date, updated_local_date, updated_nepali_date, updated_ip)
VALUES (8, 'Capital Market', 39, 'Prabhu Capital Limited', 6, 'CapitalMarket', 'Prabhu Capital Limited', '67.prabhucapital.png', 'Prabhu Capital Payment, Please enter your capital payment ID Number', NULL, NULL, NULL, NULL, 2, NULL, 'Y', '2020-04-17 16:00:06.99', '2020-04-17 21:45:06.99', '2077-01-05', 'admin', NULL, NULL, NULL, NULL, NULL, NULL)
GO

